Interface
    MDLabel:
        id: inputTemp
        halign: "center"
        text: "Hello World"
        font_style: "H4"
        theme_text_color: "Custom"
        text_color: 0,0,1,1

    MDFillRoundFlatIconButton:
        on_press: root.publica()
        icon: "apple-ios"
        text: "IOS"
        font_size: '32sp'
        pos_hint: {"center_x":0.5, "center_y":0.35} 
        icon_color: 0.5,0.3,0.2,1   